<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.ratelimit4j</groupId>
    <artifactId>ratelimit4j-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>ratelimit4j-spring-boot-starter</artifactId>
  <name>ratelimit4j :: spring-boot-starter</name>
  <description>Auto-configuration and a servlet filter that applies limiters to inbound requests.</description>

  <dependencies>
    <dependency>
      <groupId>io.ratelimit4j</groupId>
      <artifactId>ratelimit4j-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.ratelimit4j</groupId>
      <artifactId>ratelimit4j-redis</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
